# Ejercicio 1

### *Crea una funcion que dado un Array de una dimension. te haga un resumen estadistico basico de los datos. Si detecta que el array tiene mas de una dimension, tiene que mostrar un mensaje de error*

In [ ]:
import numpy as np

def inspec_array(a): # creo la funcion con la informacion estadistica basica que quiero buscar y el mensaje de error
    
    if a.ndim != 1:
        print("Error: El array tiene mas de una dimensión")
    else:
        print("Min: ", np.amin(a))
        print("Max: ", np.amax(a))
        print("Mean: ", np.mean(a))
        print("Mediana: ", np.median(a))
        print("Desviacion estandar: ", np.std(a))
        print("Varianza: ", np.var(a))

In [2]:
a = np.array([3,7,5])

inspec_array(a)

Min:  3
Max:  7
Mean:  5.0
Mediana:  5.0
Desviacion estandar:  1.632993161855452
Varianza:  2.6666666666666665


In [7]:
b = np.array([[3,7,5] , [4,8,9]])

inspec_array(b)

Error: El array tiene mas de una dimensión


# Ejercicio 2

### *Crea una funcion que te genere un cuadrado NxN de numeros aleatorios entre el 0 y el 100*

In [4]:
def cuadrado(n):
    
    a = np.random.randint(1,100,(n,n))
    print(a)

In [5]:
num = int(input("Introduce un numero: "))
cuadrado(num)

Introduce un numero: 5
[[87 93 30 25 42]
 [64 20 37 84 34]
 [19 48 73 79 20]
 [ 2 90 46 84 14]
 [38 48 10 62 57]]


In [6]:
num = int(input("Introduce un numero: "))
cuadrado(num)

Introduce un numero: 8
[[88  8 44 26 20 48 49 67]
 [12 97  1 61 17 25 94 83]
 [81 57 91 40 45 75 10 19]
 [96 97 95 25  9 79 70 78]
 [88 16 18 32 93 96  1  8]
 [50 76 82 59 91 55 77 91]
 [77 68  8 92 12 75 82 73]
 [ 7 83 87 70 27  2 81 57]]


# Ejercicio 3

### *Crea una funcion que dada una tabla de dos dimensiones, te calcule los totales por fila y los totales por columna*

In [8]:
def sumTabla(x):
    
    fila = np.sum(x, axis=0)
    colum = np.sum(x, axis=1)
    
    print("Suma fila: ", fila)
    print("Suma columna: ", colum)  

In [10]:
a = ([[4,3], [7,6]])

sumTabla(a)

Suma fila:  [11  9]
Suma columna:  [ 7 13]


# Ejercicio 4

### *Implementa manualmente una funcion que calcule el coeficiente de correlacion. Informate sobre sus usos e interpretación*